[username]
format = " [â•­â”€$user]($style)|"
style_user = "bold red"
style_root = "bold red"
show_always = true

[hostname]
format = "[$hostname]($style) in "
style = "bold dimmed red"
trim_at = "-"
ssh_only = false

[cmd_duration]
min_time = 1
format = "took [$duration]($style)"

[character]
success_symbol = " [â†’](bold red)"
error_symbol = " [Ã—](bold red)"

[battery]
full_symbol = " â•°â”€ï•¸ "
charging_symbol = " â•°â”€ï–ƒ "
discharging_symbol = " â•°â”€ï–‚ "

[[battery.display]]
threshold = 15
style = "bold red"

[[battery.display]]
threshold = 50
style = "bold yellow"

[[battery.display]]
threshold = 80
style = "bold green"

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = false

[directory]
style = "purple"
truncation_length = 0
truncate_to_repo = true
truncation_symbol = "repo: "

[git_branch]
format = " [$symbol$branch]($style) "
symbol = "ğŸ£ "
style = "bold yellow"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨ Ã—${count}"
behind = "ğŸ¢ Ã—${count}"
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count}"
untracked = "ğŸ›¤ï¸  Ã—${count}"
stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—${count}"
staged = "ğŸ—ƒï¸  Ã—${count}"
renamed = "ğŸ“› Ã—${count}"
deleted = "ğŸ—‘ï¸  Ã—${count}"
style = "bright-white"
format = "$all_status$ahead_behind"

[aws]
format = "[$symbol$version]($style) "
style = "bold red"
symbol = "îŒ½ "

[conda]
format = "[$symbol$version]($style) "
style = "bold red"
symbol = "ï„Œ "

[dart]
format = "[$symbol$version]($style) "
style = "bold red"
symbol = "î˜ "

[docker_context]
format = "[$symbol$version]($style) "
style = "bold red"
symbol = "ïŒˆ "

[elixir]
format = "[$symbol$version]($style) "
style = "bold red"
symbol = "î‰µ "

[elm]
format = "[$symbol$version]($style) "
style = "bold red"
symbol = "î˜¬ "

[golang]
format = "[$symbol$version]($style) "
style = "bold red"
symbol = "î˜§ "

[hg_branch]
format = "[$symbol$version]($style) "
style = "bold red"
symbol = "ï˜ "

[java]
format = "[$symbol$version]($style) "
style = "bold red"
symbol = "î‰– "

[julia]
format = "[$symbol$version]($style) "
style = "bold red"
symbol = "î˜¤ "

[nim]
format = "[$symbol$version]($style) "
style = "bold red"
symbol = "ïš¤ "

[nix_shell]
format = "[$symbol$version]($style) "
style = "bold red"
symbol = "ï‹œ "

[nodejs]
format = "[$symbol$version]($style) "
style = "bold red"
symbol = "î‰ "

[package]
format = "[$symbol$version]($style) "
style = "bold red"
symbol = "ï£– "

[perl]
format = "[$symbol$version]($style) "
style = "bold red"
symbol = "î© "

[php]
format = "[$symbol$version]($style) "
style = "bold red"
symbol = "î˜ˆ "

[python]
format = "[$symbol$version]($style) "
style = "bold red"
symbol = "î˜† "

[ruby]
format = "[$symbol$version]($style) "
style = "bold red"
symbol = "îˆ¾ "

[rust]
format = "[$symbol$version]($style) "
style = "bold red"
symbol = "î¨ "

[swift]
format = "[$symbol$version]($style) "
style = "bold red"
symbol = "ï¯£ "